name: Schedule Job

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight UTC

jobs:
  runs-script:
    runs-on: ubuntu-latest
    steps:
      - name: Scheduled message
        run: echo "Scheduled msg executed"
